- name: create projects folder
  file: path="~/projects/{{item}}" state=directory
  with_items:
    - python
    - test
    - nodejs
    - golang
    - software
    - docker

- name: install neovim
  yum: name=neovim state=latest

- name: install python2 dependencies
  yum: name=python2-neovim state=latest

- name: install python3 dependencies
  yum: name=python3-neovim state=latest

- name: install zsh
  command: sh -c "$(wget https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -O -)"

- name: download powerline fonts
  command: git clone https://github.com/powerline/fonts.git --depth=1 ~/projects/software/powerline

- name: install powerline fonts
  command: sh -c "~/projects/software/powerline/install.sh"

- name: change zshell theme
  command: sed -i -e '/^ZSH_THEME/s/robyrussel/wezm/g/' ~/.zshrc


