- name: create nvim folder
  file: path="~/.config/nvim" state=directory

- name: create projects folder
  file: path="~/projects/{{item}}" state=directory
  with_items:
    - python
    - test
    - nodejs
    - golang
    - software
    - docker

#- name: install neovim
#  pip: name=neovim state=latest

- name: install oh-my-zsh
  command: curl https://raw.githubusercontent.com/robbyrussell/oh-my-zsh/master/tools/install.sh -o /tmp/install.sh

- name: install oh-my-zsh - step1
  command: chmod +x /tmp/install.sh

- name: install oh-my-zsh - step2
  command: bash /tmp/install.sh

- name: download powerline fonts
  command: git clone https://github.com/powerline/fonts.git --depth=1 ~/projects/software/powerline

- name: install powerline fonts
  command: sh -c "~/projects/software/powerline/install.sh"

- name: change zshell theme
  command: sed -i -e '/^ZSH_THEME/s/robbyrussell/wezm/g' ~/.zshrc

- name: install fzf - download
  command: git clone --depth 1 https://github.com/junegunn/fzf.git ~/.fzf

- name: install fzf
  command: sh -c "~/.fzf/install"

- name: download neovim rc
  command: git clone https://github.com/manojkumarmc/vim.config ~/projects/software/vim.config

- name: cp init.vim to home directory
  command: cp ~/projects/software/vim.config/init.vim ~/.config/nvim/init.vim

- name: setup vim plug manager
  command: curl -fLo ~/.local/share/nvim/site/autoload/plug.vim --create-dirs https://raw.githubusercontent.com/junegunn/vim-plug/master/plug.vim

# - name: install vim plugins
#   command: sh -c "nvim +'PlugInstall --sync' +qa"

#- name: install virtualenv
#  pip: name=virtualenv state=latest
#
#- name: create p27 virtualenv
#  command: sh -c "virtualenv -p python2.7 ~/projects/software/p27"

- name: install ipython to p27 virtualenv
  pip: virtualenv=~/projects/software/p27 name={{item}} state=latest
  with_items:
    - hypothesis
    - requests
    - neovim
#    - ipython this needs to be seperately installed
